version: "2.2"
services:
  db:
    image: postgres:15
    container_name: db_auction
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env

  app:
    build: 
      context: .
    env_file:
      - .env
    container_name: fastapi_auction
    command: ["/int20-auction/docker/app.sh"]
    ports:
      - ${APP_PORT}:8000
    depends_on:
      - db
