"""Bet<=>Lot

Revision ID: d21755bdc4cc
Revises: 82a0eb603733
Create Date: 2024-02-08 21:39:08.689831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd21755bdc4cc'
down_revision: Union[str, None] = '82a0eb603733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('bet', sa.Column('value', sa.Double(), nullable=True))
    op.add_column('lot', sa.Column('end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lot', 'end_date')
    op.drop_column('bet', 'value')
    op.drop_column('bet', 'user_id')
    # ### end Alembic commands ###
