"""Lot relation

Revision ID: 53eef1b29bbd
Revises: 25604662ce29
Create Date: 2024-02-06 15:03:49.467770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53eef1b29bbd'
down_revision: Union[str, None] = '25604662ce29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet', sa.Column('lot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bet', 'lot', ['lot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bet', type_='foreignkey')
    op.drop_column('bet', 'lot_id')
    # ### end Alembic commands ###
