"""Add chat-fix-2

Revision ID: 93dbfc3aa14a
Revises: 8852f2718ab9
Create Date: 2024-02-06 03:28:12.700162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93dbfc3aa14a'
down_revision: Union[str, None] = '8852f2718ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
