"""Lot add categories

Revision ID: a1642dd835a2
Revises: d21755bdc4cc
Create Date: 2024-02-11 00:15:11.634602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1642dd835a2'
down_revision: Union[str, None] = 'd21755bdc4cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lot', sa.Column('lot_type', sa.String(), nullable=True))
    op.add_column('lot', sa.Column('money_aim', sa.String(), nullable=True))
    op.add_column('lot', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lot', 'image_data')
    op.drop_column('lot', 'money_aim')
    op.drop_column('lot', 'lot_type')
    # ### end Alembic commands ###
